name: CI/CD
on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps: 
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v4
      - name: Login to DockerHUB
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Construir imagen and push Docker image
        uses: docker/build-push-action@v5
        with: 
          context: ./app
          push: true
          tags: oscarbasaguren/as-laboratorio-8-web:latest
          
      - name: Start Minikube
        run: |
            sudo apt update
            sudo apt install -y minikube
            minikube start --vm-driver=none
      - name: Deploy to Minikube 
        run: |
            kubectl apply -f ./k8s/deployment-front-web.yml
            kubectl apply -f ./k8s/deployment-bd.yml
            kubectl apply -f ./k8s/redis.yml
            kubectl apply -f ./k8s/load-balancer.yml
            kubectl rollout restart deployment front-web-deployment
            kubectl rollout restart deployment db-deployment
        


